// Generated by CoffeeScript 1.3.1
(function() {

  (function($, window, document) {
    QUnit.testDone(function() {});
    return test('foobar', function() {
      var a, b;
      a = 'foobar';
      b = 'foobar';
      equal(a, b, 'foobar');
      equal(a, b, 'foobar');
      return equal(a, b, 'foobar');
    });
  })(jQuery, this, this.document);

}).call(this);
